#!/usr/bin/env bash

_comand_list(){
    local avil_commands=" --help -h  --daemon -d --update-ipv6 -6 --all -a --ttl -t --allow-ipv4-ptr-update --allow-ipv6-ptr-update "

    COMPREPLY=()

    local cur=`_get_cword`
    
    COMPREPLY=( $( compgen -W "$avil_commands" -- $cur ) )

    case "$cur" in
        -*) COMPREPLY=( $( compgen -W "$avil_commands" -- "$cur"))
        ;;
    esac

}

complete -o nosort -F _comand_list winbind-dnsupdate